# Generated by Django 4.2.11 on 2026-04-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rawingestionrecord',
            new_name='idx_source_ingestion',
            old_name='idx_raw_source_ingestion',
        ),
        migrations.RenameIndex(
            model_name='rawingestionrecord',
            new_name='idx_parse_success',
            old_name='idx_raw_parse_success',
        ),
        migrations.AlterField(
            model_name='rawingestionrecord',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
